config/routes.rb
Rails.application.routes.draw do

  root "public#login"

  devise_for :students
  get("/student_home", { :controller => "student", :action => "home" })
  # QUESTION
  get("/exam/:enrollment_id", { :controller => "student", :action => "exam" } )
  post("/create_question/:path_id", { :controller => "student", :action => "question_create" })
  post("/modify_question/:path_id", { :controller => "student", :action => "question_update" })
  get("/retake_exam/:enrollment_id", { :controller => "student", :action => "retake_exam" })

  devise_for :instructors
  get("/instructor_home", { :controller => "instructor", :action => "home" })
  # DOCUMENT
  post("/insert_document", { :controller => "instructor", :action => "document_create" })
  get("/delete_document/:path_id", { :controller => "instructor", :action => "document_destroy" })
  # SAMPLE QUESTION
  post("/insert_sample_question", { :controller => "instructor", :action => "samplequestion_create" })
  get("/delete_sample_question/:path_id", { :controller => "instructor", :action => "samplequestion_destroy" })
  # QUESTION
  get("/delete_question/:path_id", { :controller => "instructor", :action => "question_destroy" })
  #------------------------------

  # COURSE
  post("/insert_course", { :controller => "courses", :action => "create" })
  get("/courses", { :controller => "courses", :action => "index" })
  get("/courses/:path_id", { :controller => "courses", :action => "show" })
  post("/modify_course/:path_id", { :controller => "courses", :action => "update" })
  get("/delete_course/:path_id", { :controller => "courses", :action => "destroy" })
  #------------------------------

  # ENROLLMENT
  post("/insert_enrollment", { :controller => "enrollments", :action => "create" })
  get("/insert_enrollment/:query_course_id/:query_student_id", { :controller => "enrollments", :action => "create" })
  get("/enrollments/:path_id", { :controller => "enrollments", :action => "show" })
  post("/modify_enrollment/:path_id", { :controller => "enrollments", :action => "update" })
  get("/delete_enrollment/:path_id", { :controller => "enrollments", :action => "destroy" })
  #------------------------------

end

app/models/enrollment.rb
# == Schema Information
#
# Table name: enrollments
#
#  id         :bigint           not null, primary key
#  grade      :integer
#  status     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  course_id  :integer
#  student_id :integer
#
class Enrollment < ApplicationRecord

  validates :course_id, presence: true
  validates :student_id, presence: true
  validates :status, presence: true
  validates :status, inclusion: { in: [ "In Progress", "On Hold", "Passed", "Failed", "Incomplete" ] }
  validates :grade, numericality: { less_than_or_equal_to: 100, greater_than_or_equal_to: 0, allow_blank: true }
  validates :student_id, uniqueness: { scope: ["course_id"], message: "You have already enrolled for this course." }

  belongs_to :course
  belongs_to :student
  has_many  :questions, dependent: :destroy

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_student_or_instructor

  def show
    @the_enrollment = Enrollment.where({ :id => params["path_id"] }).first
    @questions = Question.where({ :enrollment_id => params["path_id"] }).order({ :created_at => :asc })
    render({ :template => "enrollments/show" })
  end

  def create
    the_enrollment = Enrollment.new
    the_enrollment.course_id = params.fetch("query_course_id")
    the_enrollment.student_id = params.fetch("query_student_id")
    the_enrollment.status = "In Progress"
    the_enrollment.grade = 0

    if the_enrollment.valid?
      the_enrollment.save
      redirect_to("/enrollments/#{the_enrollment.id}", { :notice => "Enrollment created successfully." })
    else
      redirect_to("/student_home", { :alert => the_enrollment.errors.full_messages.to_sentence })
    end
  end

  def update
    the_enrollment = Enrollment.where({ :id => params["path_id"] }).first
    the_enrollment.course_id = params.fetch("query_course_id")
    the_enrollment.student_id = params.fetch("query_student_id")
    the_enrollment.status = params.fetch("query_status")
    the_enrollment.grade = params.fetch("query_grade")

    if the_enrollment.valid?
      the_enrollment.save
      redirect_to("/enrollments/#{the_enrollment.id}", { :notice => "Enrollment updated successfully."} )
    else
      redirect_to("/enrollments/#{the_enrollment.id}", { :alert => the_enrollment.errors.full_messages.to_sentence })
    end
  end

  def destroy
    Enrollment.where({ :id => params["path_id"] }).first.destroy
    redirect_to("/student_home", { :notice => "Enrollment deleted successfully."} )
  end

  private def authenticate_student_or_instructor
    unless student_signed_in? || instructor_signed_in?
      redirect_to new_student_session_path
    end
  end
  
end

app/views/enrollments/show.html.erb
<h1>Enrollment #<%= @the_enrollment.id %> details</h1>

<div>
  <a href="/student_home">Go back</a>
  <% if student_signed_in? && current_student.id == @the_enrollment.student_id %>
    <a href="/delete_enrollment/<%= @the_enrollment.id %>">Delete enrollment</a>
    <a href="/exam/<%= @the_enrollment.id %>">Go to Exam</a>
    <a href="/retake_exam/<%= @the_enrollment.id %>">Retake Exam</a>
  <% end %>
</div>

<dl>
  <dt>Course</dt>
  <dd><a href="/courses/<%= @the_enrollment.course.id %>"><%= @the_enrollment.course.name %></a></dd>

  <dt>Student</dt>
  <dd><%= @the_enrollment.student.name %></dd>

  <dt>Status</dt>
  <dd><%= @the_enrollment.status %></dd>


  <% if (student_signed_in? && current_student.id == @the_enrollment.student_id) || (instructor_signed_in? && current_instructor.id == @the_enrollment.course.instructor_id) %>
    <dt>Grade</dt>
    <dd><%= @the_enrollment.grade %> / 30 (<%= (@the_enrollment.grade.to_f/30.0*100).round %>%)</dd>
  <% end %>

  <dt>Created at</dt>
  <dd><%= time_ago_in_words(@the_enrollment.created_at) %> ago</dd>

  <dt>Updated at</dt>
  <dd><%= time_ago_in_words(@the_enrollment.updated_at) %> ago</dd>
</dl>

<% if instructor_signed_in? && @the_enrollment.course.instructor_id == current_instructor.id %>
<hr>
<div>
  <h2>Grade student</h2>

  <form action="/modify_enrollment/<%= @the_enrollment.id %>"  method="post" >
    <div>
      <input type="hidden" id="course_id_box" name="query_course_id" value="<%= @the_enrollment.course_id %>">
      <input type="hidden" id="student_id_box" name="query_student_id" value="<%= @the_enrollment.student_id %>">
    </div>

    <div>
      <label for="status_box">Status</label>
      <select name="query_status" id="status_box">
        <option value="In Progress" <%= "selected" if @the_enrollment.status == "In Progress" %>>In Progress</option>
        <option value="On Hold" <%= "selected" if @the_enrollment.status == "On Hold" %>>On Hold</option>
        <option value="Passed" <%= "selected" if @the_enrollment.status == "Passed" %>>Passed</option>
        <option value="Failed" <%= "selected" if @the_enrollment.status == "Failed" %>>Failed</option>
        <option value="Incomplete" <%= "selected" if @the_enrollment.status == "Incomplete" %>>Incomplete</option>
      </select>
    </div>

    <div>
      <label for="grade_box">Grade</label>
      <input type="number" id="grade_box" name="query_grade" value="<%= @the_enrollment.grade %>">
    </div>

    <button>Update enrollment</button>
  </form>
</div>
<% end %>
<hr>

<% if (student_signed_in? && current_student.id == @the_enrollment.student_id) || (instructor_signed_in? && current_instructor.id == @the_enrollment.course.instructor_id) %>
<div>
  <h2>List of Questions</h2>

  <table border="1">
    <tr>
      <th>Question</th>
      <th>Given Answer</th>
      <th>Feedback</th>
      <th>Score</th>
      <th>Created at</th>
      <th>Updated at</th>
    </tr>

    <% @questions.each do |question| %>
    <tr>
      <td><%= question.question_body %></td>
      <td><%= question.student_answer %></td>
      <td><%= question.feedback %></td>
      <td><%= question.score %></td>
      <td><%= time_ago_in_words(question.created_at) %> ago</td>
      <td><%= time_ago_in_words(question.updated_at) %> ago</td>
    </tr>
    <% end %>
  </table>
</div>
<% end %>